- package.json
> Add esbuild dependency

- README.md
- schema.json
- src/plugins/cspell/README.md
- src/plugins/cspell/index.ts
- src/plugins/cspell/types.ts
- src/plugins/index.ts
- test/fixtures/plugins/cspell/.cspell.json
- test/tests/plugins/cspell.test.ts
https://www.npmjs.com/package/cspell
> feat: add new plugin cspell

- src/typescript/ast-walker.ts
> fix: add support for .d.cts and .d.mts declaration files

- tests/fixtures/subpath-import-from-plugin/.eslintrc.json
- tests/fixtures/subpath-import-from-plugin/entry.ts
- tests/fixtures/subpath-import-from-plugin/knip.json
- tests/fixtures/subpath-import-from-plugin/lib/dep-polyfill.d.ts
- tests/fixtures/subpath-import-from-plugin/lib/dep-polyfill.js
- tests/fixtures/subpath-import-from-plugin/package.json
- tests/fixtures/subpath-import-from-plugin/tsconfig.json
- tests/fixtures/subpath-import/entry.ts
- tests/fixtures/subpath-import/knip.json
- tests/fixtures/subpath-import/lib/dep-polyfill.d.ts
- tests/fixtures/subpath-import/lib/dep-polyfill.js
- tests/fixtures/subpath-import/package.json
- tests/fixtures/subpath-import/tsconfig.json
- tests/fixtures/subpath-patterns/knip.json
- tests/fixtures/subpath-patterns/package.json
- tests/fixtures/subpath-patterns/src/entry.ts
- tests/fixtures/subpath-patterns/src/internals/unused.ts
- tests/fixtures/subpath-patterns/src/internals/used.ts
- tests/fixtures/subpath-patterns/tsconfig.json
- tests/subpath-imports-from-plugin.test.ts
- tests/subpath-imports.test.ts
- tests/subpath-patterns.test.ts
closes #92
Looks like adding support for self-references also added support for these.
> test: add subpath import and subpath pattern tests

- src/index.ts
> Fix dynamic import issue with type import

- src/plugins/storybook/index.ts
- src/plugins/storybook/types.ts
- tests/fixtures/plugins/storybook/main.js
- tests/plugins/storybook.test.ts
> feat(storybook): add support for framework

- fixtures/compilers/knip.ts
- src/types/compilers.ts
- src/typescript/SourceFileManager.ts
> Pass source file path to compilers

- src/cli.ts
- src/reporters/codeowners.ts
- src/reporters/compact.ts
- src/reporters/symbols.ts
- src/types/issues.ts
a test is failing but I'm not quite sure how to fix it.
> feat: silent in CI

- fixtures/plugins/next/app/api/auth/route.ts
- fixtures/plugins/next/app/api/auth/util.ts
- fixtures/plugins/next/app/home/page.tsx
- fixtures/plugins/next/app/layout.tsx
- fixtures/plugins/next/app/unused.ts
- fixtures/plugins/next/instrumentation.ts
- fixtures/plugins/next/middleware.ts
- src/plugins/next/README.md
- src/plugins/next/index.ts
- tests/plugins/next.test.ts
> Fix entrypoints for Next.js plugin when using Next.js app router

- src/reporters/compact.ts
- src/reporters/json.ts
I did a little optimization. `map` + `flat` can be replaced by single `flatMap`.
> Simplify map+flat call

- src/plugins/typescript/index.ts
- tests/plugins/typescript.test.ts
Fixes https://github.com/webpro/knip/issues/226
> Remove react dependency requirement when using `react-jsx` in `tsconfig.json`

- README.md
- fixtures/plugins/drizzle/drizzle.config.ts
- fixtures/plugins/drizzle/node_modules/drizzle-kit/package.json
- fixtures/plugins/drizzle/node_modules/drizzle-orm/dist/pg-core.cjs
- fixtures/plugins/drizzle/node_modules/drizzle-orm/dist/pg-core.js
- fixtures/plugins/drizzle/node_modules/drizzle-orm/package.json
- fixtures/plugins/drizzle/package.json
- fixtures/plugins/drizzle/src/schema.ts
- fixtures/plugins/drizzle/src/schema/users.ts
- schema.json
- src/plugins/drizzle/README.md
- src/plugins/drizzle/index.ts
- src/plugins/drizzle/types.ts
- src/plugins/index.ts
- tests/plugins/drizzle.test.ts
Docs: https://orm.drizzle.team/kit-docs/overview
I also added `playwright-ct` to the `schema.json` file.
> drizzle plugin

- fixtures/plugins/astro/package.json
- src/plugins/astro/index.ts
- test/plugins/astro.test.ts
> Suppress report for `@astrojs/check`

- src/constants.ts
> Add `docker` to list of ignored binaries

- packages/knip/src/ConfigurationValidator.ts
- packages/knip/src/plugins/svelte/index.ts
> fix: use svelte plugin options from user config

- packages/docs/src/content/docs/features/compilers.md
closes #410
This PR adds a second, alternative recipe to the svelte compiler docs which enables Knip to accurately detect type imports that happen in svelte files.
- In svelte, you use an `export let myprop` to declare a [prop](https://svelte.dev/docs/svelte-components#script-1-export-creates-a-component-prop). So we replace all instances of `export let` with `let` to prevent knip from thinking those are actual exports.
- The implementation is admittedly hacky in that knip may see part of a file as duplicated. From testing, this does not adversely effect knip's ability to report issues. Regardless, this is why I'm suggesting it as an second alternative in the docs, rather than updating the current recipe. This way, svelte projects have a workaround at their disposal that does not require …
> docs: show an alternate method to compile svelte files

- packages/knip/src/reporters/index.ts
- packages/knip/src/reporters/markdown.ts
- packages/knip/test/cli-reporter-markdown.test.ts
this adds markdown reporter that reports the violations in markdown tables. closes #409
> feat: add markdown reporter

- package-lock.json
- packages/knip/package.json
- packages/knip/src/plugins/eslint/fallback.ts
- packages/knip/src/reporters/codeowners.ts
- packages/knip/src/reporters/symbols.ts
- packages/knip/src/reporters/util.ts
- packages/knip/src/util/debug.ts
- packages/knip/src/util/register.ts
- packages/knip/src/util/require.ts
Already used in latest postcss, autoprefixer and browserslist versions.
See https://github.com/alexeyraspopov/picocolors
> Replace chalk with picocolors

- packages/knip/src/plugins/webpack/index.ts
- packages/knip/src/util/Performance.ts
> using "forEach" instead of "map" as its return value is not being used

- packages/knip/fixtures/plugins/eleventy/eleventy.config.dynamic.cjs
- packages/knip/src/plugins/eleventy/helpers.ts
- packages/knip/src/plugins/eleventy/index.ts
- packages/knip/src/util/path.ts
- packages/knip/test/plugins/eleventy.test.ts
re: https://github.com/webpro/knip/pull/454#issuecomment-1898688280
> Handle passthrough copied files in Eleventy

- packages/docs/src/content/docs/index.mdx
[Wagmi](https://github.com/wevm/wagmi) is a popular project with 5.2k stars, and [uses and loves](https://github.com/wevm/wagmi/blob/main/package.json#L71-L112) Knip 😀
> docs: add project to index.mdx

- packages/knip/src/ConfigurationValidator.ts
Resolves #487.
Looks like a straightforward change. To be completely honest I made change directly through Github web UI so this wasn't tested.
> Add 'playwright-ct' entry to config schema

- packages/knip/src/plugins/eslint/index.ts
> Added support for eslint.config.cjs and eslint.config.mjs files

- packages/knip/fixtures/plugins/webpack/package.json
- packages/knip/fixtures/plugins/webpack/webpack.common.js
- packages/knip/src/plugins/webpack/index.ts
Added support for `Rule.oneOf` in the webpack plugin.
https://webpack.js.org/configuration/module/#ruleoneof
> Support 'oneOf' rule in webpack plugin

- packages/create-config/index.js
closes https://github.com/webpro-nl/knip/issues/724
> fix: pnpm workspace fixes

- packages/knip/src/plugins/vitest/index.ts
Resolves https://github.com/webpro-nl/knip/issues/784.
As I couldn't find any other references in the repo, I presume the docs are auto-generated? If so, nice system!
> Fix: Expand Vitest File Extension Checks

- packages/knip/src/util/modules.ts
closes https://github.com/webpro-nl/knip/issues/789
> accept _ and . in package names

- packages/knip/src/plugins/cypress/index.ts
- packages/knip/test/plugins/cypress2.test.ts
Tracks Cypress [component testing support file](https://docs.cypress.io/app/component-testing/styling-components#Component-Support-File)
> Tracks Cypress component support file

- packages/knip/fixtures/plugins/karma/karma.conf.js
- packages/knip/fixtures/plugins/karma/package.json
- packages/knip/fixtures/plugins/karma2/karma.conf.js
- packages/knip/fixtures/plugins/karma2/package.json
- packages/knip/fixtures/plugins/karma3/karma.conf.js
- packages/knip/fixtures/plugins/karma3/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/index.ts
- packages/knip/src/plugins/karma/index.ts
- packages/knip/src/plugins/karma/types.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/karma.test.ts
- packages/knip/test/plugins/karma2.test.ts
- packages/knip/test/plugins/karma3.test.ts
Add [Karma](https://karma-runner.github.io/) plugin
Features:
- Track frameworks from configuration file as dev dependencies 891b17083cc211efa59afa69c70cd49d3b9e8149
- Takes into account that in the case of Jasmine, just `jasmine-core` is needed. `jasmine` package is the CLI package. For instance, Angular projects do not install Jasmine's CLI `jasmine` package, given `ng test` is used instead. This can be [clearly seen in `karma-jasmine` plugin code](https://github.com/karma-runner/karma-jasmine/blob/v5.1.0/lib/index.js#L8)
- Track test files from configuration file as non-production entry points by reading `basePath` / `files` 3849e47195b47da801d85e46f3b97f7e2748473d
- ~Not taking into account `exclude` for now. Could be improved later. Jest plugin doesn't take ignore configurations …
> Add Karma plugin

- packages/knip/src/constants.ts
[npm's `zip` package](https://www.npmjs.com/package/zip) last release is from 11 years ago. Though still has 26k downloads a week. Anyway what you probably want is to zip something with the CLI binary.
> Ignore `zip` global binary

- packages/knip/src/plugins/storybook/index.ts
> support .mts files in storybook config and project

- packages/docs/src/content/docs/guides/handling-issues.mdx
> Remove a wrong "not" in handling-issues.mdx

- packages/knip/fixtures/plugins/create-typescript-app/create-typescript-app.config.js
- packages/knip/fixtures/plugins/create-typescript-app/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/create-typescript-app/index.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/create-typescript-app.test.ts
> feat: add create-typescript-app plugin

- packages/knip/fixtures/plugins/i18next-parser/custom.config.js
- packages/knip/fixtures/plugins/i18next-parser/i18next-parser.config.js
- packages/knip/fixtures/plugins/i18next-parser/node_modules/i18next-parser/package.json
- packages/knip/fixtures/plugins/i18next-parser/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/i18next-parser/index.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/i18next-parser.test.ts
Added a plugin to detect config files for the i18next-parser (https://github.com/i18next/i18next-parser).
> Add i18next-parser plugin

- packages/knip/src/plugins/lint-staged/index.ts
Follow up to feedback in #1045.
Issue: #1048
> refactor(lint-staged): remove unneeded default packageJsonPath value

- packages/knip/src/plugins/prettier/index.ts
Prettier now supports TS configs:
https://prettier.io/docs/configuration
> Support Prettier TypeScript configs

- packages/knip/README.md
> Fix contributors link in README.md

- packages/knip/fixtures/plugins/docusaurus/docusaurus.config.js
- packages/knip/fixtures/plugins/docusaurus/docusaurus.config.ts
- packages/knip/fixtures/plugins/docusaurus/node_modules/@docusaurus/core/package.json
- packages/knip/fixtures/plugins/docusaurus/package.json
- packages/knip/fixtures/plugins/docusaurus/src/pages/index.js
- packages/knip/schema.json
- packages/knip/src/DependencyDeputy.ts
- packages/knip/src/graph/build.ts
- packages/knip/src/plugins/docusaurus/helpers.ts
- packages/knip/src/plugins/docusaurus/index.ts
- packages/knip/src/plugins/docusaurus/types.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/src/util/input.ts
- packages/knip/test/plugins/docusaurus.test.ts
This adds a plugin for [Docusaurus](https://docusaurus.io/). 
Issue: #1056
> feat: add Docusaurus plugin

- packages/docs/src/content/docs/reference/plugins.md
- packages/knip/fixtures/plugins/changelogen/changelog.config.ts
- packages/knip/fixtures/plugins/changelogen/node_modules/changelogen/package.json
- packages/knip/fixtures/plugins/changelogen/package.json
- packages/knip/fixtures/plugins/changelogithub/changelogithub.config.ts
- packages/knip/fixtures/plugins/changelogithub/node_modules/changelogithub/package.json
- packages/knip/fixtures/plugins/changelogithub/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/changelogen/index.ts
- packages/knip/src/plugins/changelogithub/index.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/src/util/plugin-config.ts
- packages/knip/test/plugins/changelogen.test.ts
- packages/knip/test/plugins/changelogithub.test.ts
Added the Changelogen plugin.
https://github.com/unjs/changelogen
This is a popular changelog generation tool.
Also added support for loading c12 configs:
https://github.com/unjs/c12
I am currently having a problem when using Changelogen configs:
```
> eslint-rule-benchmark@0.2.0 test:usage /Users/azat/Developer/eslint-rule-benchmark
> knip
Unused files (1)
changelog.config.ts 
```
> Add Changelogen and Changelogithub plugins

- packages/knip/fixtures/plugins/nx/libs/b/project.json
- packages/knip/src/plugins/nx/index.ts
- packages/knip/src/plugins/nx/types.ts
Fixes https://github.com/webpro-nl/knip/issues/1078. I'm not certain about what changes should be introduced to the tests file 🤔.
> Add support for NX rich command structure

- packages/knip/src/plugins/sentry/index.ts
- packages/knip/test/plugins/sentry.test.ts
Fixes #1103.
I couldn't see any corresponding tests to update. Let me know if there's something I should add.
> Mark sentry config files as production entrypoints

- packages/knip/test/plugins/_template.test.ts
Following-up from https://github.com/webpro-nl/knip/pull/1113#discussion_r2120038310 so contributors are aware of knip's approach to testing.
> Update plugin test template

- packages/knip/src/binaries/package-manager/bun.ts
> Add `audit` as a valid command for bun

- packages/docs/src/content/docs/overview/features.md
Just a quick fix for a broken link.
> Fix related-tooling.md link

- packages/knip/fixtures/plugins/nuxt/nuxt.config.ts
- packages/knip/fixtures/plugins/nuxt/package.json
- packages/knip/src/plugins/nuxt/index.ts
- packages/knip/src/plugins/nuxt/types.ts
> feat: detect nuxt modules as dependencies

- packages/knip/fixtures/plugins/rsbuild/rsbuild.config.ts
- packages/knip/src/plugins/rsbuild/index.ts
- packages/knip/src/plugins/rsbuild/types.ts
- packages/knip/test/plugins/rsbuild.test.ts
See https://rsbuild.rs/guide/advanced/environments
> Update `rsbuild` Plugin to Check Environments

- packages/knip/src/binaries/package-manager/bun.ts
> fix: bun ci

- packages/knip/fixtures/plugins/pnpm2/package.json
- packages/knip/src/plugins/pnpm/index.ts
- packages/knip/test/plugins/pnpm2.test.ts
Take into account `pnpm-lock.yaml` & `pnpm-workspace.yaml` for enabling the pnpm plugin.
> fix: enable pnpm plugin on root config & lockfile

- packages/knip/fixtures/plugins/bumpp/node_modules/bumpp/package.json
- packages/knip/fixtures/plugins/bumpp/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/bumpp/index.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/bumpp.test.ts
Adds plugin for [`bumpp`](https://github.com/antfu-collective/bumpp#bumpp)
> feat: add plugin for `bumpp`
