- src/plugins/typedoc/index.ts
- src/plugins/typedoc/types.ts
- test/fixtures/plugins/typedoc/typedoc.json
fix #64 
re https://github.com/webpro/knip/commit/73c3c5f5f706f4c8c1f24a585801674092f0a4eb#r102767065
> fix: name of property typedoc plugins are specified in

- src/util/fs.ts
- src/util/loader.ts
rc files can often be written in either yaml or json so knip so try loading them as both.
As yaml is a super type of json. Any valid json can be parsed with the yaml parser - so it's more performant to try this one first. jsonc isn't valid yaml though so we still need to try the json parser if the yaml one fails.
> fix: parse rc configs with no extension as either yaml or json

- src/plugins/svelte/README.md
- src/plugins/svelte/index.ts
SvelteKit has this notion of layout resets in the `src/routes` folder. It adds `@` as a reset character after e.g. `+page` or `+layout` that can be followed by name of layout group or file. These were reported as unused files by knip.
> - `+page@[id].svelte` - inherits from `src/routes/(app)/item/[id]/+layout.svelte`
> - `+page@item.svelte` - inherits from `src/routes/(app)/item/+layout.svelte`
> - `+page@(app).svelte` - inherits from `src/routes/(app)/+layout.svelte`
> - `+page@.svelte` - inherits from `src/routes/+layout.svelte`
You can find more here https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-breaking-out-of-layouts .
> fix(svelte): layout reset reported as false positive (unused file)

- src/plugins/tailwind/index.ts
If a project had `type: module` in `package.json`.
We had to provide `tailwind.config.cjs` to work.
> Update tailwindcss plugin with .cjs support

- package.json
Hey 👋
Thanks a lot for this fantastic tool, it's **very** helpful.
I noticed that you set a fixed version of `typescript` as dependency, resulting on downloading TS 5.0.2 **and** 5.0.3.
I don't see why it should be fixed (maybe there's a reason? 😅), so I made this PR.
Thanks!
> Unfix typescript version

- .eslintrc
- package.json
- src/typescript/createHosts.ts
- src/util/path.ts
- tests/plugins/jest.test.ts
- tests/plugins/webpack.test.ts
Hey, just saw your update and wanted to point out that `eslint-plugin-node` is no longer maintained. The newer version is `eslint-plugin-n`. Keep up the great work!
https://www.npmjs.com/package/eslint-plugin-n
> Change eslint-plugin-node to eslint-plugin-n

- src/plugins/postcss/index.ts
- tests/fixtures/plugins/postcss-next/node_modules/postcss-rtlcss/index.js
- tests/fixtures/plugins/postcss-next/node_modules/postcss-rtlcss/package.json
- tests/fixtures/plugins/postcss-next/package.json
- tests/fixtures/plugins/postcss-next/postcss.config.json
`next.js` [allows ](https://nextjs.org/docs/pages/building-your-application/configuring/post-css) to declare postcss-config like this
```
{
"plugins": [
"postcss-flexbugs-fixes",
[
"postcss-preset-env",
{
"autoprefixer": {
"flexbox": "no-2009"
},
"stage": 3,
"features": {
"custom-properties": false
}
}
]
]
}
```
so I add more checks to detect packages
> feat(postcss): enhance dependencies detection

- src/ConfigurationValidator.ts
Now, if you use the TypeScript version of the config file and customize the issue types for "binaries", an error occurs. This is a microfix
> feat: add binaries type in config validator

- @types/bash-parser/index.d.ts
- package.json
- src/binaries/bash-parser.ts
Relates to #72 - Replaces [`bash-parser`](https://www.npmjs.com/package/bash-parser) by my own fork of the project [`@ericcornelissen/bash-parser`](https://www.npmjs.com/package/@ericcornelissen/bash-parser).
With this fork I aim to provide dependency maintenance. Thus far this only covers the removal of a non-OSI package, namely [`curry`](https://www.npmjs.com/package/curry), from the dependency tree.
Do note that this fork does not promise to provide anything beyond dependency maintenance. A proper replacement of `bash-parser` should be preferred if available.
> Replace `bash-parser` by `@ericcornelissen/bash-parser`

- src/plugins/jest/index.ts
Ignore file names starting with `$` from `moduleNameMapper` in the Jest plugin.
> Ignore $ strings in `moduleNameMapper` in the Jest plugin

- README.md
- src/util/cli-arguments.ts
For reference, it seems to be accomplished by the `process.stdout.isTTY` value, which is set to undefined in CI (i.e. GitHub Actions).
> docs: document ci + show-progress

- fixtures/plugins/vitest/vitest2.config.ts
- src/plugins/vitest/index.ts
- tests/plugins/vitest.test.ts
Vitest has a default coverage provider, v8, but knip detects it as an unused dependency.
We can safely assume the user uses Vitest's coverage if the config file contains the `coverage` field, so this PR uses `v8` as the default provider if `provider` is not set.
https://vitest.dev/guide/coverage.html#coverage-providers
> fix(vitest): support default coverage provider

- src/plugins/webpack/index.ts
This fixes a crash I was getting in my project based on Razzle.js, because the Webpack plugin code wasn't handling all of the cases that can happen in the configuration's `entry` field. (Specifically, when the entry is an object and its keys are of type `string[]`.)
This is also a little more defensively written and (IMO) easier to understand.
Based on the TS types here:
https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/types.d.ts#L2396-L2400
> webpack: handle a couple more cfg.entry formats

- fixtures/nextjs/next.config.js
- fixtures/nextjs/package.json
- fixtures/nextjs/src/app/page.tsx
- fixtures/nextjs/src/middleware.ts
- fixtures/nextjs/tsconfig.json
- src/plugins/next/README.md
- src/plugins/next/index.ts
- tests/nextjs.test.ts
NextJS supports a feature named [middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware). However, the plugin for Next does not list middleware.ts as a possible entry point causing knip command to fail (example repo [here](https://github.com/surbina/nextjs-middleware-knip-test)).
This PR adds middleware.ts as possible entry point to the NextJS plugin. It also adds a test to validate it's working as expected.
> fix: add middleware.ts to default nextjs config plugin

- src/PrincipalFactory.ts
`Array.from` has optional second argument. Calling `map` is not required for this case.
> Simplify array.from+map

- src/manifest/index.ts
Spread creates a new array in each iteration, resulting in a complexity of O(n*n). Using `push` has a complexity of O(n) and does not create a new array.
> Optimize findManifestDependencies

- README.md
- fixtures/cli-preprocessor/node_modules/with-args/index.ts
- fixtures/cli-preprocessor/node_modules/with-args/package.json
- src/cli.ts
- src/types/issues.ts
- src/util/cli-arguments.ts
- tests/cli-preprocessor.test.ts
Adds a `--preprocessor-options` flag, to allow preprocessors to access separate options from reporters. I've opted to pass it in as a separate preprocessorOptions parameter, so that preprocessors still have access to the eventual reporter options.
I can change it to use the options field instead if preferred.
> feat: add --preprocessor-options flag

- src/plugins/next/index.ts
I have a `page.ts` file that simply performs a redirect without involving JSX. It's also possible that a page simply re-exports a component defined elsewhere.
> Mark .ts files as entrypoints inside Next.js app dir

- src/plugins/typescript/README.md
- src/plugins/typescript/index.ts
The `tsconfig.*.json`, often used when you have multiple `tsconfig` per project, is common enough in the ecosystem so I think that's a reasonable addition.
`typescript-eslint` is a good example: https://typescript-eslint.io/linting/typed-linting/monorepos/#one-root-tsconfigjson
> add `tsconfig.*.json` pattern to the typescript plugin

- src/plugins/storybook/README.md
- src/plugins/storybook/index.ts
The test hook api is configurable using the `.storybook/test-runner.{js,ts}` file.
Docs: https://storybook.js.org/docs/react/writing-tests/test-runner#test-hook-api-experimental
> Add support for Storybook test runner's hook api

- README.md
- fixtures/plugins/playwright-ct/node_modules/@playwright/experimental-ct-react/package.json
- fixtures/plugins/playwright-ct/package.json
- fixtures/plugins/playwright-ct/playwright-ct.config.ts
- fixtures/plugins/playwright-ct/playwright/index.html
- fixtures/plugins/playwright-ct/playwright/index.tsx
- fixtures/plugins/playwright-ct/test/some.spec.ts
- src/plugins/index.ts
- src/plugins/playwright-ct/README.md
- src/plugins/playwright-ct/index.ts
- tests/plugins/playwright-ct.test.ts
Playwright now supports component testing which uses a different config + dependencies: https://playwright.dev/docs/test-components
> Playwright for components plugin

- fixtures/plugins/jest/jest.config.js
- src/plugins/jest/index.ts
- tests/plugins/jest.test.ts
Dependencies such as [jest-sonar-reporter](https://www.npmjs.com/package/jest-sonar-reporter) are used in the `testResultsProcessor` config from jest, and are currently not being considered as used dependency by knip.
This PR adds that configuration to the jest's plugin for resolving jest's dependencies.
> Add jest's `testResultsProcessor` to dependency check

- src/plugins/next/index.ts
https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#generate-icons-using-code-js-ts-tsx
`-image` part is not present for icons.
> Fix pattern for icons in Next apps

- src/plugins/gatsby/README.md
- src/plugins/gatsby/index.ts
Gatsby allows "local plugins" in the plugins folder that don't exist as full proper workspaces, but instead are run by Gatsby itself. This PR modifies the Gatsby plugin to include the "local plugins" folders by default, so these are included.
Plugins don't have a gatsby-config like the main site does, so I made the config entry only take the gatsby-node file.
> feat: allow gatsby plugin to see local plugins as entrypoints

- src/reporters/json.ts
I'm currently working on a simple github action that will comment on a PR with the report outputs from the JSON report and noticed that the `binaries` field was missing in the json blob.
Also noticed a small mistake in the documentation around the report keys
> Add binaries to JSON reporter

- fixtures/plugins/nx/apps/b/project.json
- fixtures/plugins/nx/package.json
- src/plugins/nx/index.ts
Since nx version 16, they changed their npm scope from `@nrwl/*` to `@nx/*`. I've added a change to ensure both are detected.
See more about this change [here](https://nx.dev/recipes/other/rescope).
> Support new Nx npm scope

- fixtures/plugins/postcss-cjs/node_modules/autoprefixer/index.js
- fixtures/plugins/postcss-cjs/node_modules/autoprefixer/package.json
- fixtures/plugins/postcss-cjs/node_modules/postcss/package.json
- fixtures/plugins/postcss-cjs/package.json
- fixtures/plugins/postcss-cjs/postcss.config.cjs
- src/plugins/postcss/README.md
- src/plugins/postcss/index.ts
- test/plugins/postcss-cjs.test.ts
Fixes #256
Right now, the postcss dosn't support a `.cjs` file name, this PR fixes that !
I'v added : 
Feel free to request any changes you see fit !
> Support postcss cjs file format

- src/constants.ts
It is Bun's `npx` (https://bun.sh/docs/cli/bunx)
> Add `bunx` to list of ignored binaries

- packages/knip/fixtures/plugins/prettier/package.json
- packages/knip/src/plugins/prettier/index.ts
- packages/knip/test/plugins/prettier.test.ts
Prettier supports using a dependency as configuration, as mentioned in [their documentation](https://prettier.io/docs/en/configuration.html#sharing-configurations), and is currently not being detected by knip.
This PR detects if this configuration type is being used, and adds it to the dependency list.
> adds support for `package.json` shared prettier configuration

- packages/knip/fixtures/plugins/vitest-npm-script/package.json
- packages/knip/fixtures/plugins/vitest-npm-script/vitest.config.ts
- packages/knip/src/plugins/vitest/index.ts
- packages/knip/test/plugins/prettier.test.ts
- packages/knip/test/plugins/vitest-npm-script.test.ts
This fixes #372 by doing base searches for either `--coverage` or `coverage.enabled=true` for commands starting with `vitest`. This should be good enough but does not account for e.g. npx or for overriding the [coverage instrumenter](https://github.com/search?q=--coverage.provider&type=code) in the command line arguments.
<details>
<summary>Unfortunately the "test" script in the root did not work for me</summary>
```js
node --no-warnings --test tmp
node:internal/modules/cjs/loader:1147
throw err;
^
Error: Cannot find module '/home/dany/dev/forks/knip/packages/knip/tmp'
at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
at Module._load (node:internal/modules/cjs/loader:985:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
at …
```
> vitest: Detect whether coverage is enabled in npm scripts

- packages/knip/src/ConfigurationChief.ts
It is possible that the manifest workspaces include the root workspace. In this case `ConfigurationChie#getAvailableWorkspaceNames()` would return the root name twice. This in turn would result in the root package being included twice and throw a `ConfigurationError` because of a duplicate package name.
To address this we deduplicate the workspace names.
I’d be happy to add some tests for this but I’d need some guidance where the best spot for these would be.
Fixes #390
> Deduplicate workspace names

- packages/knip/fixtures/plugins/svelte/src/hooks.client.ts
- packages/knip/fixtures/plugins/svelte/src/hooks.server.ts
- packages/knip/fixtures/plugins/svelte/src/params/lang.ts
- packages/knip/src/plugins/svelte/index.ts
- packages/knip/test/plugins/svelte.test.ts
This PR's adds more sveltekit entry patterns:
1. sveltekit's two optional hooks [files](https://kit.svelte.dev/docs/hooks)
2. param [matchers](https://kit.svelte.dev/docs/advanced-routing#matching)
Before this PR, knip reports the files as "unused files" (if they exist).
Additionally, I've expanded the pattern for vite.config.* (to help with this workaround: https://github.com/webpro/knip/issues/346#issuecomment-1807689199)
> add sveltekit entry patterns

- packages/knip/src/plugins/next/index.ts
The [global-error](https://nextjs.org/docs/app/api-reference/file-conventions/error#global-errorjs) entry file is missing in the Next.js plugin.
> Add Next.js global-error entry file

- packages/docs/remark/fixInternalLinks.ts
- links in content: `/entry-files/` (ends with slash `/`)
- from sidebar link:  `/entry-files` (not ends with slash)
Thus, the result of specifying a link by relative paths will be different.
For example, the following cases will not transition correctly.
1. https://knip.dev/overview/getting-started/
2. click Reference Plugins (in sidebar)
3. click any plugin link
4. 404 page not found
So I unified url without slash.
> fix: docs internal link replacement

- packages/docs/src/content/docs/explanations/plugins.md
- packages/knip/src/plugins/vitest/index.ts
- packages/knip/test/plugins/vitest-npm-script.test.ts
- packages/knip/test/plugins/vitest.test.ts
Vitest by default [accepts *.test-d.ts files as type tests](https://vitest.dev/guide/testing-types#testing-types). This is not included in the Knip Vitest plugin so it currently reports such files as unused.
> fix: add .test-d to vitest entry files

- packages/knip/fixtures/plugins/unbuild/build.config.ts
- packages/knip/fixtures/plugins/unbuild/package.json
- packages/knip/schema.json
- packages/knip/src/ConfigurationValidator.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/plugins/unbuild/index.ts
- packages/knip/src/plugins/unbuild/types.ts
- packages/knip/test/plugins/unbuild.test.ts
Adds a plugin for [unbuild](https://github.com/unjs/unbuild). This is a super simple plugin since AFAIK there isn't any other dependencies you can use with unbuild... is there a simpler way to ignore unbuild config files automatically? Is it worth having this as a plugin?
> Add `unbuild` plugin

- packages/knip/src/plugins/next/index.ts
This allows nextjs route handlers to include JSX Syntax, I noticed that knip marks these files as unused, as I use JSX route handlers to send emails with react-email. 
I also noticed that there is no allowed pattern for the `default.{js,ts,tsx,jsx}` files yet.
- fix: allow router handlers to be jsx files, add default.{js,jsx,ts,tsx}
> Update allowed files in Next.js

- packages/knip/src/util/debug.ts
- packages/knip/src/util/loader.ts
In the case of checking if a file path ends with `rc`, `filePath.endsWith("rc")` is likely to be faster. This is because it's a straightforward string comparison without the need for the more complex pattern matching capabilities of regular expressions.
> use the 'String#endsWith' method instead

- packages/knip/fixtures/plugins/eleventy/eleventy.config.cjs
- packages/knip/fixtures/plugins/eleventy/eleventy.config.dynamic.cjs
- packages/knip/src/plugins/eleventy/helpers.ts
- packages/knip/src/plugins/eleventy/index.ts
- packages/knip/src/plugins/eleventy/types.ts
- packages/knip/test/plugins/eleventy.test.ts
> Add Eleventy data directory as entry pattern

- packages/knip/fixtures/plugins/eleventy2/.eleventy.js
- packages/knip/src/plugins/eleventy/index.ts
Resolves https://github.com/webpro/knip/pull/460#issuecomment-1900344718. Would love to hear your thoughts on this.
> Check for node_modules presence instead of isInternal for Eleventy plugin

- packages/knip/src/plugins/eleventy/index.ts
I seem to have forgotten to add the `.mjs` extension earlier. You can see the official supported list here: https://github.com/11ty/eleventy/blob/main/src/TemplateConfig.js#L72-L75
> Update Eleventy plugin config paths

- packages/knip/fixtures/plugins/nx-crystal/nx.json
- packages/knip/fixtures/plugins/nx-crystal/package.json
- packages/knip/src/plugins/nx/index.ts
- packages/knip/src/plugins/nx/types.ts
- packages/knip/test/plugins/nx-crystal.test.ts
This Pr add support for the [Nx crystal project](https://dev.to/nx/what-if-nx-plugins-were-more-like-vscode-extensions-4oh0) to detect dependancies from nx.json.
I have added tests to ensure the feature works as intended.
This is a very basic support, only reading the nx.json to detect the plugins that are required.
A more advanced support would be to read the nx graph to get the computed, infered, targets to detect the run commands used. Given this will impact Knip larger (to have to import the `@nx/devkit`, to then get the actual graph), I didn't go this far _yet_. If you think this could be useful, let me know and I will open a second pr for this work! And also let me know the strategy you prefer (await import() or not, peer, optional peer or dev dependancy only, ...) given there is no …
> feat: support nx crystal for nx plugin

- packages/knip/src/constants.ts
As the same as `@types/node`, ignore `@types/bun`.
Since `bun-types` is not supposed to install directly as stated in the [npm package docs](https://www.npmjs.com/package/bun-types), we do not need to ignore `bun-types`.
> Ignore @types/bun by default

- packages/docs/src/content/docs/features/reporters.md
- packages/knip/src/reporters/markdown.ts
- packages/knip/test/cli-reporter-markdown.test.ts
- make the output valid for prettier
- add line+col to the location of issue
- add severity as it's own column
> feat: improve markdown reporter

- packages/knip/src/plugins/cypress/index.ts
https://docs.cypress.io/api/cypress-api/custom-commands
"We recommend defining queries is in your cypress/support/commands.js file, since it is loaded before any test files are evaluated via an import statement in the [supportFile](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file)."
> Add support for  cypress/support/commands.js file

- packages/knip/fixtures/plugins/nx-crystal/nx.json
- packages/knip/src/plugins/nx/index.ts
- packages/knip/src/plugins/nx/types.ts
- packages/knip/test/plugins/nx-crystal.test.ts
Nx plugins syntax allows for using standalone `string` identifiers and not only objects. This pr addresses that to ensure knip works with string and not only the object syntax.
[Here is the json schema for the plugin key in the `nx.json` config : 
](https://github.com/nrwl/nx/blob/master/packages/nx/schemas/nx-schema.json#L499)
```json
"plugins": {
"oneOf": [
{
"type": "string",
"description": "A plugin module to load with default options"
},
{
"type": "object",
"properties": {
"plugin": {
"type": "string",
"description": "The plugin module to load"
},
"options": {
"type": "object",
"description": "The options passed to the plugin when creating nodes and dependencies"
}
}
}
]
},
```
> fix: make nx crystal work with standalone plugins

- packages/knip/src/reporters/json.ts
Hello - I noticed that when using `--reporter=json` on a project with a lot of unused code the JSON output was truncated. This seems to be due to this known issue, a combination of large output (> 65k) followed by `process.exit()`. See this issue: https://github.com/nodejs/node/issues/6379.
I've applied the workaround documented in that (and related) issues.
Let me know if you think I should write a test for it.
> fix truncated JSON output with JSON reporter

- packages/knip/src/version.ts
- packages/knip/test/cli.test.ts
Hi! This PR bumps the constant string in `version.ts` and updates the test implementation to ensure that the string doesn't get out of sync with `package.json` again.
I may or may not have gone on a goose chase through my NPM setup when `knip --version` was return 4.4.0 earlier today.
> Fix knip --version command

- packages/knip/src/ConfigurationValidator.ts
- packages/knip/src/types/config.ts
Currently `include` and `exclude` options in config are of type `string[]`. But these are already validated by `zod` to conform to `issueTypeSchema`, e.g. `files`, `dependencies` etc.
This PR improves types of `include` and `exclude` so that allowed values could be type-checked and also improves config discoverability without the need to refer to the docs.
> Improve configuration of `include/exclude` types for better discoverability

- packages/docs/src/content/docs/features/compilers.md
- packages/knip/src/ConfigurationValidator.ts
Fixes https://github.com/webpro/knip/issues/547
Compilers receive a filename string as their second argument, I believe this is the correct place in the zod schema to provide the definition so that they'll be available in typing.
> Add documented type for second string arg to compilers

- packages/knip/fixtures/plugins/wrangler/node_modules/wrangler/package.json
- packages/knip/fixtures/plugins/wrangler/package.json
- packages/knip/fixtures/plugins/wrangler/wrangler.toml
- packages/knip/schema.json
- packages/knip/src/ConfigurationValidator.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/plugins/wrangler/index.ts
- packages/knip/src/plugins/wrangler/types.ts
- packages/knip/test/plugins/wrangler.test.ts
Hi :wave:,
This PR aims to implement a plugin for Cloudflare Workers, or more specifically their `wrangler` cli. The config file is `wrangler.toml` with json config in experimental status (has been for quite a while), and contains one relevant entry, the main entrypoint of the worker.
I think I managed to add a correctly minimal fixture this time, the new config api made it even simpler compared to the Astro one :tada:, great work!
> Add wrangler plugin

- packages/knip/src/plugins/next/index.ts
- packages/knip/test/plugins/next.test.ts
This is currently flagged as a false positive since any `default.tsx` or `default.jsx` file is not included in the entry point of the project but are also not imported since this is a special next.js file which marks it as unused by knip.
> fix: add jsx extensions for next default file convention

- package-lock.json
- package.json
- packages/docs/package.json
- packages/eslint-config/package.json
I used `knip` as a good project to verify the latest addition of workspace support in my [`installed-check`](https://github.com/voxpelli/node-installed-check) module, and I thought I could just as well send a PR in case you are interested in running it yourself.
It mainly verifies that one doesn't promise more in `engines.node` than what ones dependencies can back up, but it also has checks for whether one is running an outdated `node_modules` installation (as else the other data will be wrong as it uses the locally installed data for verification) and whether one promises a wider peer dependency range than what ones dependencies does (not applicable to this project)
Running it in verbose mode (`--verbose / -v`) shows that there are a couple of dependencies who are not publishing a …
> Add engine field verification with `installed-check`

- packages/docs/src/content/docs/explanations/plugins.md
- packages/docs/src/content/docs/explanations/why-use-knip.md
- packages/docs/src/content/docs/features/auto-fix.mdx
- packages/docs/src/content/docs/features/compilers.md
- packages/docs/src/content/docs/features/reporters.md
- packages/docs/src/content/docs/guides/handling-issues.mdx
I saw a few typos while browsing the docs, so here's some fixes for them :slightly_smiling_face:
> Fix typos in docs

- packages/knip/fixtures/plugins/commitlint/.commitlintrc.json
- packages/knip/fixtures/plugins/commitlint/commitlint.config.js
- packages/knip/fixtures/plugins/commitlint/package.json
- packages/knip/src/plugins/commitlint/index.ts
- packages/knip/test/plugins/commitlint.test.ts
Currently, knip only supports commitlint extends, but [not plugins](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/types/src/load.ts#L30). This pr aims to fix that
> feat: support commitlint plugins key

- packages/knip/fixtures/plugins/vitest3/vitest.config.ts
- packages/knip/src/plugins/vitest/helpers.ts
Previously, knip reported build in reporters (such as `basic`) as third parties librarires. This pr aims to resolve this
> feat: support all vitest built in reporters

- packages/knip/fixtures/plugins/babel/.babelrc.js
- packages/knip/src/plugins/babel/index.ts
Babel supports importing or directly declaring plugins in the JS configuration. Currently `knip` will throw an error trying to parse the plugin name if a plugin/preset is directly imported.
Example config directly from babel monorepo: https://github.com/babel/babel/blob/main/babel.config.js#L199
I'm not sure if `knip` will actually handle the `require`/`import` in JS babel configs yet, but this at least makes it not throw.
> fix(plugin/babel): bypass directly required plugins or presets in babel config

- packages/knip/src/plugins/next/index.ts
This is unfortunately undocumented like most next.js quirks but this does work if you are making an og image route handler kinda like the `opengraph-image` convention but with less magic
> fix: next route handler extensions

- packages/knip/fixtures/plugins/xo/.xo-config.js
- packages/knip/fixtures/plugins/xo/node_modules/xo/package.json
- packages/knip/fixtures/plugins/xo/package.json
- packages/knip/fixtures/plugins/xo/xo-config.cjs
- packages/knip/schema.json
- packages/knip/src/ConfigurationValidator.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/plugins/xo/index.ts
- packages/knip/src/plugins/xo/types.ts
- packages/knip/test/plugins/xo.test.ts
Adds a plugin for [xo](https://github.com/xojs/xo#config). Essentially its an opinionated wrapper around eslint with a bunch of bundled rules and plugins, and the config object is just the eslint config object with some extra options. So to keep it consistent with the eslint plugin and avoid duplication I've just used the eslint helper to parse out any additional eslint plugins that have been added in the xo config.
> feat(plugins): add plugin for xo config

- packages/knip/fixtures/plugins/syncpack/package.json
- packages/knip/schema.json
- packages/knip/src/ConfigurationValidator.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/plugins/syncpack/index.ts
- packages/knip/test/plugins/syncpack.test.ts
> Add plugin for syncpack 

- packages/knip/fixtures/plugins/commitlint/.commitlintrc.json
- packages/knip/fixtures/plugins/commitlint/commitlint.config.js
- packages/knip/src/plugins/commitlint/index.ts
- packages/knip/src/plugins/commitlint/types.ts
- packages/knip/test/plugins/commitlint.test.ts
> fix(plugin-commitlint): handling of `parserPreset` when it's not a string

- packages/knip/src/util/fs.ts
> fix: isFile/isDirectory edge cases

- packages/knip/fixtures/plugins/unocss/main.ts
- packages/knip/fixtures/plugins/unocss/node_modules/@unocss/cli/index.js
- packages/knip/fixtures/plugins/unocss/node_modules/@unocss/cli/package.json
- packages/knip/fixtures/plugins/unocss/node_modules/unocss/index.js
- packages/knip/fixtures/plugins/unocss/node_modules/unocss/package.json
- packages/knip/fixtures/plugins/unocss/package.json
- packages/knip/fixtures/plugins/unocss/unocss.config.ts
- packages/knip/schema.json
- packages/knip/src/ConfigurationValidator.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/plugins/unocss/index.ts
- packages/knip/src/plugins/unocss/types.ts
- packages/knip/test/plugins/unocss.test.ts
> Add UnoCSS plugin

- packages/knip/src/plugins/webpack/index.ts
Adds support for Webpack config files that specify entries with an absolute path.
> Webpack plugin: support absolute entry paths

- packages/knip/fixtures/workspaces-complex-module-resolution/node_modules/@monorepo/workspaceA
- packages/knip/fixtures/workspaces-complex-module-resolution/node_modules/@monorepo/workspaceB
- packages/knip/fixtures/workspaces-complex-module-resolution/package.json
- packages/knip/fixtures/workspaces-complex-module-resolution/packages/workspaceA/package.json
- packages/knip/fixtures/workspaces-complex-module-resolution/packages/workspaceA/src/index.ts
- packages/knip/fixtures/workspaces-complex-module-resolution/packages/workspaceA/tsconfig.json
- packages/knip/fixtures/workspaces-complex-module-resolution/packages/workspaceB/package.json
- packages/knip/fixtures/workspaces-complex-module-resolution/packages/workspaceB/src/exports.ts
- packages/knip/fixtures/workspaces-complex-module-resolution/packages/workspaceB/src/index.ts
- packages/knip/fixtures/workspaces-complex-module-resolution/packages/workspaceB/src/used-fn.ts
- packages/knip/fixtures/workspaces-complex-module-resolution/packages/workspaceB/tsconfig.json
- packages/knip/fixtures/workspaces-complex-module-resolution/tsconfig.json
- packages/knip/src/index.ts
- packages/knip/src/typescript/resolveModuleNames.ts
- packages/knip/test/workspaces-complex-module-resolution.test.ts
Still draft until I can figure out why some tests are failing on github but not local.
This PR is my attempt to fix #610.
- Do not save module resolution failures in the `resolutionCache` of `resolveModuleNames.ts` so that a failed attempt to resolve a file in the wrong principal doesn't block resolution in the right principal from succeeding
- Analyze scripts rescursively in main analysis loop so they can be handled within the principal they belong to and don't get mixed up with the `internalWorkspaceFilePaths`
- Analyze all `internalWorkspaceFilePaths` after analyzing all of the principals and lookup which principal each belongs to
- Small adjustments to the way analyzed files are excluded from repeat processing to simplify code changes above
> Fix module resolution across multiple dependent workspaces with incompatible tsconfigs 

- packages/knip/fixtures/fix-workspaces/exports.ts
- packages/knip/fixtures/fix-workspaces/ignored.ts
- packages/knip/fixtures/fix-workspaces/index.js
- packages/knip/fixtures/fix-workspaces/knip.ts
- packages/knip/fixtures/fix-workspaces/package.json
- packages/knip/fixtures/fix-workspaces/packages/ignored/exports.ts
- packages/knip/fixtures/fix-workspaces/packages/ignored/index.js
- packages/knip/fixtures/fix-workspaces/packages/ignored/package.json
- packages/knip/fixtures/fix-workspaces/packages/lib/exports.ts
- packages/knip/fixtures/fix-workspaces/packages/lib/ignored.ts
- packages/knip/fixtures/fix-workspaces/packages/lib/index.js
- packages/knip/fixtures/fix-workspaces/packages/lib/package.json
- packages/knip/fixtures/fix/ignored.ts
- packages/knip/fixtures/fix/index.js
- packages/knip/fixtures/fix/knip.ts
- packages/knip/fixtures/fix/mod.ts
- packages/knip/fixtures/fix/package.json
- packages/knip/src/IssueCollector.ts
- packages/knip/src/index.ts
- packages/knip/test/fix-workspaces.test.ts
- packages/knip/test/fix.test.ts
Closes https://github.com/webpro-nl/knip/issues/653
Fixed and added test cases for the following cases
- `ignore`.
- ignoreDependencies`
- use `ignoreWorkspaces` for ignore
- `tags` for ignore
Since `ignoreMembers` is not yet supported by Auto-fix and I thought `ignoreBinaries` was an option unrelated to Auto-fix, I did not include either of them in the test case.
> fix(Auto-fix): ignore is not applied

- packages/knip/src/constants.ts
Hello! 👋  It seems we list a lot of unix commands as available binaries already so I thought `kill` and `ssh` would be fair game. Let me know if not.
> Add ‘kill’ and ‘ssh’ as globally available binaries

- packages/knip/src/constants.ts
> Add ‘aws’ as globally available binary

- packages/docs/src/content/docs/reference/configuration.md
As mentioned in #668, the documentation for the `ignoreBinaries` confused me and lead me to use it for an unintended side effect. I hope the change makes it clear what the configuration option is for.
> Better explain `ignoreBinaries` configuration option

- packages/knip/fixtures/plugins/vitest4/node_modules/vitest/config.js
- packages/knip/fixtures/plugins/vitest4/node_modules/vitest/package.json
- packages/knip/fixtures/plugins/vitest4/package.json
- packages/knip/fixtures/plugins/vitest4/src/index.ts
- packages/knip/fixtures/plugins/vitest4/src/unused.test.ts
- packages/knip/fixtures/plugins/vitest4/tests/adder.test.ts
- packages/knip/fixtures/plugins/vitest4/tests/setup.ts
- packages/knip/fixtures/plugins/vitest4/vitest.config.ts
- packages/knip/src/plugins/vitest/index.ts
- packages/knip/src/plugins/vitest/types.ts
- packages/knip/test/plugins/vitest4.test.ts
This adds support for the [Vitest `root` config](https://vitest.dev/config/#root). Without it, valid `vitest.config.ts` and `vitest.workspace.ts` files were being improperly parsed.
Existing fixtures and tests are still passing. Added a new test to prove `root` does indeed change the relative path in which files are include (incl. global and setup files).
> Add missing `root` property to vitest

- packages/knip/fixtures/plugins/husky-v9/.husky/pre-commit
- packages/knip/src/constants.ts
Hey, firstable thanks for this awesome project!
'command' is part of npm https://www.npmjs.com/package/command, but it's not maintained (last publish 10 years ago). 'command' is also a unix command that, for example, can check if a command is available in the current shell. This creates a false positive whenever 'command' is used.
We use it for example inside of a husky pre-commit hook like this:
```bash
if ! command -v yalc check &> /dev/null
then
echo "yalc could not be found"
exit
fi
```
This results in knip flagging this as a unlisted binary:
```
Unlisted binaries (1)
command  .husky/pre-commit
```
I've added a test for this in the husky v9 fixture, but it's actually not really related to husky, because this could be used in any kind of bash script. If there is a better place for this …
> feat: add command to ignored binaries

- packages/knip/src/plugins/lockfile-lint/index.ts
The dot before `lockfile-lint.config.js` is not a supported config.
Not in cosmiconfig v8 & v9.
The list of supported configs is actually larger: 
https://github.com/lirantal/lockfile-lint/blob/main/packages/lockfile-lint/README.md#file-based-configuration
https://github.com/cosmiconfig/cosmiconfig?tab=readme-ov-file#cosmiconfig
But that is out of scope for this bugfix.
> Fix lockfile-lint config filename

- packages/knip/src/plugins/cypress/index.ts
Cypress config can support the value of `false` for both the `e2e.supportFile` and `component.supportFile` settings
https://docs.cypress.io/guides/references/configuration#e2e
https://docs.cypress.io/guides/references/configuration#component
Because `false` is neither a `string` nor `Array<string>`, when transformed by the map in line 31, `toEntryPattern` tries to perform `specifier.replace(/^(entry:)?/, 'entry:')` which gives the error `TypeError: specifier.replace is not a function`
> Fix: Support Cypress configs with `false` value for `e2e.supportFile` and `component.supportFile`

- packages/knip/src/plugins/graphql-codegen/index.ts
- packages/knip/test/plugins/graphql-codegen-graphql-config.test.ts
- packages/knip/test/plugins/graphql-codegen.test.ts
This ensures knip finds references to graphql-codegen plugins with plugin-level configuration, and can detect these as used, unused or unlisted dependencies.
> Add support for graphql-codegen plugin level config (resolves #692)

- packages/knip/src/typescript/visitors/dynamic-imports/importCall.ts
We see the following exception when running the latest versions of `knip`
```
file:///Users/christian/project/node_modules/knip/dist/typescript/visitors/dynamic-imports/importCall.js:33
else if (ts.isObjectBindingPattern(arg.name)) {
^
TypeError: Cannot read properties of undefined (reading 'name')
at file:///Users/christian/project/node_modules/knip/dist/typescript/visitors/dynamic-imports/importCall.js:33:72
at file:///Users/christian/project/node_modules/knip/dist/typescript/visitors/index.js:4:35
```
Version: Any version >[5.22.1](https://github.com/webpro-nl/knip/releases/tag/5.22.1)
Root cause: https://github.com/webpro-nl/knip/commit/1343826aa56bc70da74e9d79648329439ce010d8#diff-4f5da9f532afb6319ca695a791c6d09766d095bdb5e2466bd1aa989e58823ebbR47
Even with `--debug` I wasn't able to …
> Fix Cannot read properties of undefined (reading 'name')

- packages/docs/scripts/generate-plugin-docs.ts
Before (currently live https://knip.dev/reference/plugins/cucumber): 
After: 
Sidenote: The edit link that gets generated on these pages is misleading
> fix: Use `parseFragment` instead of `text` node which breaks formatting

- packages/knip/fixtures/plugins/graphql-codegen/codegen.ts
- packages/knip/src/plugins/graphql-codegen/index.ts
- packages/knip/test/plugins/graphql-codegen.test.ts
Closes https://github.com/webpro-nl/knip/issues/729
> (plugin/GraphQL Codegen): Support full name for plugin and preset

- packages/knip/fixtures/plugins/cypress-multi-reporter/cypress.config.ts
- packages/knip/fixtures/plugins/cypress-multi-reporter/cypress/support/commands.ts
- packages/knip/fixtures/plugins/cypress-multi-reporter/cypress/support/e2e.ts
- packages/knip/fixtures/plugins/cypress-multi-reporter/node_modules/@nrwl/cypress/plugins/cypress-preset.js
- packages/knip/fixtures/plugins/cypress-multi-reporter/node_modules/cypress/index.js
- packages/knip/fixtures/plugins/cypress-multi-reporter/node_modules/cypress/package.json
- packages/knip/fixtures/plugins/cypress-multi-reporter/package.json
- packages/knip/fixtures/plugins/cypress-multi-reporter/reporter-config.json
- packages/knip/src/plugins/cypress/helpers.ts
- packages/knip/src/plugins/cypress/index.ts
- packages/knip/src/plugins/cypress/types.ts
- packages/knip/test/plugins/cypress-multi-reporter.test.ts
> feat(cypress): add support for cypress-multi-reporter

- packages/create-config/index.js
This refactor improves the detection of workspace configurations by adding a check for Yarn workspaces. The function now returns the appropriate flag (`-w/W`) for both Yarn and PNPM workspaces, ensuring correct package installation in multi-package repositories.
closes https://github.com/webpro-nl/knip/issues/754
> Extract getWorkspaceFlag(pm) to also detect Yarn workspace configurations

- .gitattributes
This PR:
- Adds webp and otf, because "assets/cow-with-orange-scissors-van-gogh-style.webp" and "packages/docs/public/fonts/SourceSansPro-Regular.otf" are in the repo.
- Adds comments explaining why the values are there.
- Alphabetizes the list.
> chore: update gitattributes with more file types

- packages/knip/src/util/glob-core.ts
- packages/knip/test/util/parse-and-convert-gitignore-patterns.test.ts
Just started using `knip` today and it was instrumental in some really nice cleanup in our codebase. I hit #795 right off the bat, though, and it took me a while to figure out what was going on. I figured I could say "thanks" by opening up a quick PR to fix the issue!
The logic in the gitignore parser that strips trailing `# ...` off of `.gitignore` lines appears to be wrong. In my testing, you cannot add a comment to the end of a `.gitignore` line in this manner (syntax highlighting be damned):
```gitignore
dist # this is not a comment
```
This tracks with [git's documentation](https://git-scm.com/docs/gitignore) (emphasis mine) as well as my own messing around with git:
> A line **starting** with # serves as a comment. Put a backslash (`\`) in front of the **first** hash for patterns …
> Do not treat trailing `#` in gitignore as comment

- packages/knip/fixtures/plugins/stylelint/.stylelintrc
- packages/knip/src/plugins/stylelint/index.ts
- packages/knip/src/plugins/stylelint/types.ts
- packages/knip/test/plugins/stylelint.test.ts
Closes #799 
Adds `customSyntax` to the stylelint plugin. Includes a test case.
> Stylelint plugin - fix issue where "customSyntax" property is not recognised as a resolved dependency

- packages/docs/src/content/docs/reference/known-issues.md
As mentioned in #811, the imports for icons when using the `unplugin-icons` package are virtual and cannot be resolved by Knip so this PR documents the "workaround" of using the `paths` config option to point to the types so that they can be resolved properly.
> Add documentation for unplugin-icons imports issue

- packages/knip/src/constants.ts
Amplify is an AWS app framework. It has two generations (gen1 and gen2).
Setup docs for gen1 suggest installing `amplify` command globally:
https://docs.amplify.aws/gen1/javascript/tools/cli/start/set-up-cli/
`npm install -g @aws-amplify/cli`
Installing this package locally does not make sense because it contains a binary that weights a few _hundred_ megs.
They completely changed the architecture in Amplify gen2 (which is pretty recent):
https://docs.amplify.aws/javascript/start/quickstart/
New CLI is called `ampx` and originates from `@aws-amplify/backend-cli`. I haven’t used Amplify gen2 but I _guess_ that this dependency is now meant to be local (which makes sense).
---
This PR is addressing a false positive for Amplify gen1.
```
Unlisted binaries (1)
amplify  package.json    
```
It’s …
> Add `amplify` to `IGNORED_GLOBAL_BINARIES`

- packages/knip/package.json
Fix for https://github.com/webpro-nl/knip/issues/820
> Fix knip chrasing due to invalid picocolors version

- packages/knip/src/plugins/github-actions/index.ts
Skip checking a github action step if its not an array as its possibly a templated string.
In gh actions a valid config is `${{ toJSON(steps) }}` which breaks the plugins parsing. if we see a string we should just skip those steps
> Skip indexing into a gh action if its not an array

- packages/docs/src/content/docs/explanations/comparison-and-migration.md
Fixed `npm-check` link in `Related projects` block
> Update comparison-and-migration.md. Fix wrong link of npm-check

- packages/knip/fixtures/plugins/jest2/jest.config.js
- packages/knip/fixtures/plugins/jest2/jest.environment.js
- packages/knip/src/plugins/jest/index.ts
- packages/knip/test/plugins/jest2.test.ts
Adds support for custom `testEnvironment` files like:
```ts
testEnvironment:
'<rootDir>/tests/framework/e2e/jest-environments/E2EEnvironment.ts',
```
I get a unit test failure on the cli version when running the tests locally. Maybe it'll pass in CI. Anyone know how to fix that?
> jest: support custom testEnvironment

- packages/knip/fixtures/plugins/jest/customSuiteProperties.cjs
- packages/knip/fixtures/plugins/jest/jest.config.js
- packages/knip/fixtures/plugins/jest/junitProperties.js
- packages/knip/fixtures/plugins/jest2/junitTestCaseProperties.js
- packages/knip/fixtures/plugins/jest2/package.json
- packages/knip/fixtures/plugins/jest2/project1/customProperties.cjs
- packages/knip/fixtures/plugins/jest2/project1/jest.config.js
- packages/knip/src/plugins/jest/helpers.ts
- packages/knip/src/plugins/jest/index.ts
- packages/knip/test/plugins/jest.test.ts
- packages/knip/test/plugins/jest2.test.ts
Adds support for resolving dependencies from `jest-junit` reporter configuration.
See https://github.com/jest-community/jest-junit?tab=readme-ov-file#configuration
Files declared through the combination of
```
testCasePropertiesFile,
testCasePropertiesDirectory,
testSuitePropertiesFile,
testSuitePropertiesDirectory,
```
from `jest-jsunit` configuration are now correctly reported as used.
- The code is a bit involved. We might want to consider moving resolving reporters like this to it's own file or directory separate from the plugin?
- I'm pretty sure according to the docs that both files are always required when `jest-jsunit` is used. They both have default values in the configuration. But could be good to just double check so we don't report unused files incorrectly if these files don't …
> Support resolving jest-junit file dependencies

- packages/knip/src/constants.ts
> fix: add `scp` to `IGNORED_GLOBAL_BINARIES`

- packages/knip/src/plugins/angular/index.ts
- packages/knip/test/plugins/angular2.test.ts
Tracks Angular's server side rendering server entrypoint file as a production file. 
Defined in Angular CLI's `@angular-devkit/build-angular:application` builder [`server` option](https://github.com/angular/angular-cli/blob/19.0.2/packages/angular/build/src/builders/application/schema.json#L19)
> [!NOTE]
> This is the first of a series of PRs to improve the Angular plugin so that it works out-of-the-box for freshly baked Angular apps.
> 
> Checkout the analysis and following steps in https://github.com/davidlj95/a19-knip
>
> I'll update types in the next PR, as seems many types have changed with recent updates.
> Track Angular's `server` builder option

- packages/knip/src/plugins/angular/types.ts
- packages/knip/src/plugins/angular/update-types.sh
Seems Angular CLI workspace file `angular.json` types has been updated with some additions around. This adds the new types using the same `json-schema-to-typescript` approach. 
Adds a small shell script to help updating that file in the future. Let me know if JS is preffered. I'm more used to writing shell scripts, but can give try writing one using Node.js / `bun`'s compatible `child_process.exec`
> Update Angular workspace types and add update script

- packages/knip/fixtures/plugins/angular2/angular.json
- packages/knip/fixtures/plugins/angular2/src/browser.ts
- packages/knip/fixtures/plugins/angular2/src/environments/environment.development.ts
- packages/knip/fixtures/plugins/angular2/src/environments/environment.ts
- packages/knip/src/plugins/angular/index.ts
- packages/knip/src/plugins/angular/types.ts
- packages/knip/test/plugins/angular2.test.ts
Tracks Angular [environment specific files](https://angular.dev/tools/cli/environments#using-environment-specific-variables-in-your-app) as entry points.
Takes into account:
- If file replacements are part of a production configuration or not to add them as production entries or not.
- Previous syntax for Webpack-based browser application builder (`src/replaceWith` instead of `replace/with`).
- File replacements out of `configurations`. As they're technically correct and work. However, it's not a common use case. The purpose of environment files is to apply different ones depending on the configuration, not apply them for all cases (hence part of the builder options). Also those aren't used if a configuration specifies some `fileReplacements`.
> Track Angular environment files as entry points

- packages/knip/src/plugins/astro/index.ts
Hi there 👋 
Astro v5 changed the location of the content collection config from `src/content/config.ts` to `src/content.config.ts`, although it still support the old location.
From the [official migration page](https://docs.astro.build/en/guides/upgrade-to/v5/#legacy-v20-content-collections-api):
> Add new content configuration entry for Astro

- packages/knip/fixtures/plugins/expo/app.config.ts
- packages/knip/fixtures/plugins/expo/node_modules/expo/package.json
- packages/knip/fixtures/plugins/expo/package.json
- packages/knip/fixtures/plugins/expo2/app.config.js
- packages/knip/fixtures/plugins/expo2/node_modules/expo/package.json
- packages/knip/fixtures/plugins/expo2/package.json
- packages/knip/fixtures/plugins/expo3/app.json
- packages/knip/fixtures/plugins/expo3/node_modules/expo/package.json
- packages/knip/fixtures/plugins/expo3/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/expo/helpers.ts
- packages/knip/src/plugins/expo/index.ts
- packages/knip/src/plugins/expo/types.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/expo.test.ts
- packages/knip/test/plugins/expo2.test.ts
- packages/knip/test/plugins/expo3.test.ts
This PR adds a plugin for [Expo](https://docs.expo.dev/).
Features
- Adds entry files based on whether `expo-router` (A file-based router akin to NextJS) is used or not.
- ~~Adds `expo`, `react`, and `react-native` as dependencies; required for all Expo projects.~~
- Adds dependencies from plugins listed in Expo config file
- Adds dependencies that are implied from other config options
- Adds dependencies from certain packages that only need to be installed to be picked up by Expo. For example, installing `expo-dev-client` will cause Expo to use the package when building the native app; it does not need to referenced or imported anywhere other than the `package.json`.
> Add `expo` plugin

- packages/knip/src/WorkspaceWorker.ts
After [upgrading Knip to latest version 5.41.1 from 5.38.2 in an Angular project](https://github.com/davidlj95/website/pull/921) found out that a file that was previously correctly tracked as production entry was suddenly appearing as unused file (specifically, `src/main.ts`) when using knip in production mode. I've been working with the Angular plugin recently, so first thought was I may have messed up something. That file is added as production entry because appears in `browser` option of the `build` target in `angular.json`. 
However, that piece of code hasn't changed and the file should be added as production entry. After manually bisecting which version introduced the bug, seems it appears in [5.39.2](https://github.com/webpro-nl/knip/releases/tag/5.39.2). In there, there's a [plugin …
> Always run config resolver

- packages/knip/fixtures/plugins/angular/package.json
- packages/knip/fixtures/plugins/angular2/angular.json
- packages/knip/fixtures/plugins/angular2/package.json
- packages/knip/src/plugins/angular/index.ts
- packages/knip/src/plugins/angular/types.ts
- packages/knip/src/plugins/karma/helpers.ts
- packages/knip/src/plugins/karma/index.ts
- packages/knip/test/plugins/angular.test.ts
- packages/knip/test/plugins/angular2.test.ts
Angular allows running tests using Karma via the [`@angular-devkit/build_angular:karma` builder](https://github.com/angular/angular-cli/tree/19.0.6/packages/angular_devkit/build_angular/src/builders/karma). However, configuration in Angular CLI workspace (aka `angular.json`) using that builder to run tests using Karma isn't taken into account as Karma configuration. But this is something that comes built-in when creating a fresh Angular project. This PR aims to take into account that builder configuration for `knip`.
To do so:
- **Karma plugin has been refactored**: so that common functionality shared by both plugins lives in `helpers.ts`. In the same fashion that XO uses some ESLint helpers. The code to load a configuration file has been moved there too to keep clean the `index.ts` file. …
> Add Karma configuration from Angular plugin configuration

- packages/knip/src/constants.ts
[npm's `rsync` package](https://www.npmjs.com/package/rsync) last release is from 8 years ago. Though still has 35k downloads a week. Anyway what you probably want is to `rsync` something with the CLI binary.
> Ignore `rsync` global binary

- packages/knip/fixtures/plugins/angular/angular.json
- packages/knip/src/plugins/angular/index.ts
- packages/knip/test/plugins/angular.test.ts
Several Angular CLI builders allow to specify a [`scripts` option](https://github.com/angular/angular-cli/blob/19.0.6/packages/angular/build/src/builders/application/schema.json#L78) in its configuration. Those files will be included in the build and optionally added to `index.html`. Track them as production entries\*.
> \* Though they may not be production entries! They'll probably be production entries if they are part of the `build` target. 
> Same happens for other configuration options. Like `main`, which can be specified in many `build` targets but also on non-production `test` target. 
> Options `browser`, `ssr.entry` or `server` could also be specified in other targets other than `build` and they won't probably be production entries. Opening another PR for that
> Track Angular scripts build option

- packages/knip/fixtures/plugins/nx/libs/b/project.json
- packages/knip/src/plugins/nx/index.ts
- packages/knip/src/plugins/nx/types.ts
- packages/knip/test/plugins/nx.test.ts
Nx supports a shorthand for defining commands, without the need to specify an executor. It's documented under Examples > Shorthand here: https://nx.dev/nx-api/nx/executors/run-commands
> Add support for nx command shorthand to nx plugin

- .github/DEVELOPMENT.md
- packages/knip/src/index.ts
On a large number of files, knip is crashing with out-of-memory. This is caused by the fact that all of the source file text and programs are being held for the entirety of the processing.
There is an explicit factory.deletePrincipal being done after every principal is processed, in the `!isIsolateWorkspaces && isSkipLibs && !isWatch` case, but the `principals` array is still holding onto the principal, so the memory is not released.
As we iterate through the principals, I clear the entry if it is deleted. I chose to set the principals entry to `undefined`, rather than manipulating the list, for code simplicity.
> Delete principal from array after usage for GC

- packages/knip/fixtures/plugins/metro/metro.config.js
- packages/knip/fixtures/plugins/metro/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/index.ts
- packages/knip/src/plugins/metro/index.ts
- packages/knip/src/plugins/metro/types.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/metro.test.ts
This adds a plugin for [Metro](https://metrobundler.dev/), the JavaScript bundler for React Native.
> Add `metro` plugin

- packages/knip/fixtures/plugins/angular3/angular.json
- packages/knip/fixtures/plugins/angular3/package.json
- packages/knip/src/plugins/angular/index.ts
- packages/knip/src/plugins/angular/types.ts
- packages/knip/test/plugins/angular3.test.ts
> ~~This is a work in progress. #886 should be merged first to take that into account too. #884 should be merged first too in order for production mode to run.~~ ✅ 
Some of the entry files added as part of Angular plugin are added as production entries. However they may not be production entries. Hence causing production mode to not work as expected.
Configuration for building an Angular project is usually specified under the `build` target inside the `architect` object of the Angular CLI workspace (aka `angular.json`). However, right now the implementation is using configuration options from all targets. Which is good to capture also build options like when building for testing within the `test` target. However, in that scenario, the entries added should be non-production ones.
Also, in …
> Separate Angular production vs non-production entries

- packages/knip/fixtures/plugins/dependency-cruiser/.dependency-cruiser.js
- packages/knip/fixtures/plugins/dependency-cruiser/baseline.config.js
- packages/knip/fixtures/plugins/dependency-cruiser/custom-depcruise-config.js
- packages/knip/fixtures/plugins/dependency-cruiser/dependency-cruise.config.js
- packages/knip/fixtures/plugins/dependency-cruiser/node_modules/dependency-cruiser/package.json
- packages/knip/fixtures/plugins/dependency-cruiser/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/dependency-cruiser/index.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/dependency-cruiser.test.ts
> feat: add dependency-cruiser plugin

- packages/create-config/index.js
Pull request #738 introduced a call to `git rev-parse` which crashes when trying to run `npm init @knip/config` on a repository not using git. This pull request swallows errors from `git rev-parse` and reverts to the previous behavior in case calling `git rev-parse` throws an exception. The `stdio` option is to hide stderr, otherwise we get a scary error message (`fatal: not a git repository (or any of the parent directories): .git`).
I’ve tried it on an SVN repository and it seems to work as expected. Closes #752.
> Do not crash when running npm init @knip/config on a repository not using git

- packages/knip/src/plugins/jest/index.ts
jest allows defining manual mocks within a special __mocks__ directory, so those files should be seen as used by knip. See: https://jestjs.io/docs/manual-mocks
> feat(jest): add __mocks__ to entry files

- packages/knip/src/util/to-source-path.ts
I _think_ this fixes logic that has a bug but due to incorrect parenthesis in a ternary with a nullish coalescing operator. When a `rootDir` is specified in tsconfig.json that is something other than the value `"src"`, the `rootDir` config is not honored. In my case, I _do_ have a `src` dir, but it's unrelated to my TypeScript source which is located elsewhere (where my `rootDir` poins to). Knip ends up forcing the workspace `srcDir` value to `"src"` due to this bug combined with the presence of a `src` directory.
I attempted to add a test, but I'm not so familiar with the codebase and could not seem to exercise the right code paths 😞, but can give it another try if needed.
> fix: ensure augmentWorkspace honors tsConfig rootDir

- packages/knip/fixtures/plugins/eslint/eslint.config.ts
- packages/knip/fixtures/plugins/eslint/node_modules/@eslint/js/index.js
- packages/knip/fixtures/plugins/eslint/node_modules/@eslint/js/package.json
- packages/knip/fixtures/plugins/eslint/node_modules/eslint/index.js
- packages/knip/fixtures/plugins/eslint/node_modules/eslint/package.json
- packages/knip/fixtures/plugins/eslint/package.json
- packages/knip/src/plugins/eslint/index.ts
- packages/knip/test/plugins/eslint.test.ts
Adds support for eslint.config.ts files to the eslint plugin's default configuration.
https://eslint.org/docs/latest/use/configure/configuration-files#typescript-configuration-files
https://github.com/webpro-nl/knip/issues/955
> feat(plugin-eslint): support eslint.config.ts files

- packages/create-config/index.js
Hi! I'm trying out knip but I failed to make it work. This PR should make the error readable:
```
Error: Command failed: yarn add -W -D knip typescript @types/node
at genericNodeError (node:internal/errors:983:15)
at wrappedFn (node:internal/errors:537:14)
at checkExecSyncError (node:child_process:882:11)
at execSync (node:child_process:954:15)
at main (file:///private/var/folders/nq/5sbqxy457yj6_x1_28c_x2sr0000gp/T/xfs-c03b4532/dlx-61726/node_modules/@knip/create-config/index.js:49:3)
at file:///private/var/folders/nq/5sbqxy457yj6_x1_28c_x2sr0000gp/T/xfs-c03b4532/dlx-61726/node_modules/@knip/create-config/index.js:58:1
at ModuleJob.run (node:internal/modules/esm/module_job:273:25)
at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:600:26)
at async …
```
> fix(create-config): updated script for latest Yarn version

- packages/docs/src/content/docs/features/reporters.md
- packages/knip/src/reporters/codeclimate.ts
- packages/knip/src/reporters/gitlab.ts
- packages/knip/src/reporters/index.ts
- packages/knip/test/cli/reporter/cli-reporter-codeclimate.test.ts
- packages/knip/test/cli/reporter/cli-reporter-codeclimate2.test.ts
- packages/knip/test/cli/reporter/cli-reporter-codeclimate3.test.ts
- packages/knip/test/cli/reporter/cli-reporter-codeclimate4.test.ts
- packages/knip/test/helpers/assertAndRemoveProperty.ts
This adds a built-in reporter for the GitLab Code Quality Report format.
I took the json reporter as template and adapted it to print json in the GitLab format.
Because this format does not support reporting multiple issues in one entry, I decided to create multiple entries for the 'duplicates' issue type.
> feat: add Gitlab Code Quality Reporter

- packages/knip/src/constants.ts
This changes allows for functions like these ones without getting an error:
```json
{
"clean": "bun run clean:win || bun run clean:lin",
"clean:win": "node -e \"process.exit(process.platform === 'win32' ? 0 : 1)\" && cmd /c del /Q dockstatapi.db* && echo 'success'",
"clean:lin": "node -e \"process.exit(process.platform !== 'win32' ? 0 : 1)\" && rm -f dockstatapi.db* && echo 'success'"
}
```
> Allow for windows cmd commands

- bun.lock
- package.json
- packages/knip/package.json
- packages/knip/src/reporters/codeclimate.ts
- packages/knip/test/cli/reporter/cli-reporter-codeclimate.test.ts
- packages/knip/test/cli/reporter/cli-reporter-codeclimate2.test.ts
- packages/knip/test/cli/reporter/cli-reporter-codeclimate3.test.ts
- packages/knip/test/cli/reporter/cli-reporter-codeclimate4.test.ts
This replaces the custom CodeClimate types with the `codeclimate-types` package. Reusing existing types is less error prone that maintaining them internally.
This change uncovered that end positions were missing. This doesn’t affect GitLab, which doesn’t use this information (yet), but it might affect other tooling that expects it.
> Use codeclimate-types

- packages/docs/tsconfig.json
By default the MDX language server uses `remark-frontmatter` and `remark-gfm`. However, knip uses `remark-directive` as well. This leads to syntax errors in the editor. By explicitly specifying these plugins in `tsconfig.json`, we instruct the language server to load this plugin too, making the syntax errors disappear.
> Configure MDX IntelliSense

- packages/knip/src/reporters/codeclimate.ts
CodeClimate fingerprints should uniquely identify the issue. The problem with using positional information is that though it adds to the uniqueness, it significantly reduces the identification part.
To clarify, let’s say we have the following file:
```js
// file.js
export function used() {}
export function unused() {}
```
The function `unused` is detected as unused by knip. The hash is calculated from:
- `'/runner/file.js'` (filePath)
- `'unused'` (message)
- `54` (pos)
Let’s say this results in the hash `abc`.
This hash has two problematic factors:
1. It depends on an absolute path, which is system dependant. For example a GitLab users may switch to a different runner or Docker image.
2. If any characters are inserted or deleted before `unused`, the fingerprint changes.
Let’s say the …
> Avoid position to calculate CodeClimate fingerprint

- packages/knip/fixtures/plugins/stylelint/.stylelintrc
- packages/knip/fixtures/plugins/stylelint2/myCustomPlugin.js
- packages/knip/fixtures/plugins/stylelint2/stylelint.config.js
- packages/knip/src/plugins/stylelint/index.ts
- packages/knip/src/plugins/stylelint/types.ts
- packages/knip/test/plugins/stylelint2.test.ts
close https://github.com/webpro-nl/knip/issues/963
> fix: Fix custom stylelint plugin causes knip crash

- packages/knip/fixtures/plugins/vitest8/node_modules/vitest/config.js
- packages/knip/fixtures/plugins/vitest8/node_modules/vitest/package.json
- packages/knip/fixtures/plugins/vitest8/package.json
- packages/knip/fixtures/plugins/vitest8/src/index.test.ts
- packages/knip/fixtures/plugins/vitest8/vitest.config.ts
- packages/knip/src/plugins/vitest/index.ts
- packages/knip/src/plugins/vitest/types.ts
- packages/knip/test/plugins/vitest8.test.ts
The `vitest` plugin is not properly handling [workspace configurations](https://vitest.dev/guide/workspace.html).
This PR should enable that, and thus detect various things (e.g. `globalSetup`, `setupFiles`, `reporters` or `coverage.provider`) inside a `workspace` array - like in this example:
```ts
import { defineConfig } from 'vitest/config';
export default defineConfig({
test: {
workspace: [
{
test: {
name: 'integration',
setupFiles: './vitest.integration.setup.mjs',
},
},
{
test: {
globalSetup: './vitest.unit.setup.ts',
name: 'unit',
},
},
],
},
});
```
> feat: handle vitest workspace configuration

- packages/knip/fixtures/plugins/react-router/app/routes.ts
- packages/knip/src/plugins/react-router/index.ts
- packages/knip/test/plugins/react-router.test.ts
The `react-router` plugin currently seems to ignore route files with `(` or `)` in their path, since these are [interpreted as special characters](https://www.npmjs.com/package/fast-glob#advanced-syntax) by `micromatch` (and thus `fast-glob`).
I put together a small repo that shows the issue here: https://github.com/rossipedia/knip-optional-path-routes
The simplest fix I could think of was to just use a regex to escape any of those characters found in the loaded route file paths, since they were discovered via the file-system I think it makes sense to treat them as literal paths with any special characters having been escaped.
> fix: escape react-router route paths

- packages/knip/src/plugins/simple-git-hooks/index.ts
- packages/knip/test/plugins/simple-git-hooks.test.ts
Hello!
I get an error when using knip:
```
Unused devDependencies (1)
simple-git-hooks  package.json:66:6
```
The plugin does not seem to be working correctly at the moment. This PR marks the simple-git-hooks dependency as used when the config exists.
> Mark simple-git-hooks as used dependency when config exists

- packages/knip/src/plugins/next/index.ts
In version v15.3, Next.js introduced a new [Client Instrumentation Hook](https://nextjs.org/blog/next-15-3#client-instrumentation-hook) instrumentation-client.js|ts. I reported this change in #1034.
This PR closes #1034.
> Add 'instrumentation-client' to next plugin entry points

- packages/knip/src/plugins/next/index.ts
When using `@next/mdx`, the user must define a module named `mdx-components`.
> Mark mdx-components as an entry file for Next.js

- packages/docs/src/content/docs/reference/plugins.md
- packages/knip/fixtures/plugins/svgo/node_modules/svgo/package.json
- packages/knip/fixtures/plugins/svgo/package.json
- packages/knip/fixtures/plugins/svgo/svgo.config.js
- packages/knip/schema.json
- packages/knip/src/plugins/index.ts
- packages/knip/src/plugins/svgo/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/svgo.test.ts
Hello.
I am using SVGO for SVG minification on my project [(example)](https://github.com/azat-io/eyecons). In the root of my project there is a config for SVGO, which is marked as unused file:
```
Unused files
svgo.config.js  
```
The implementation follows the pattern of other similar plugins:
- Created plugin in `packages/knip/src/plugins/svgo/`
- Added test suite with fixtures
- Registered plugin in main plugin index
- Configuration logic recognizes standard SVGO config files
Documentation has been generated for the plugin using the standard docs generation scripts.
> Add SVGO plugin

- packages/knip/fixtures/plugins/postcss-tailwindcss2/node_modules/postcss/package.json
- packages/knip/fixtures/plugins/postcss-tailwindcss2/node_modules/tailwindcss/package.json
- packages/knip/fixtures/plugins/postcss-tailwindcss2/package.json
- packages/knip/fixtures/plugins/postcss-tailwindcss2/postcss.config.mjs
- packages/knip/src/plugins/postcss/index.ts
- packages/knip/test/plugins/postcss-tailwindcss2.test.ts
Tailwind v4 [docs](https://tailwindcss.com/docs/installation/using-postcss) recommend using the `@tailwindcss/postcss` plugin, but the current code only handles the `tailwindcss` plugin. The following changes add support for both plugins.
This PR is heavily based on #764.
> (PostCSS plugin): Add postcss to used dependencies when using `@tailwindcss/postcss` plugin

- packages/knip/fixtures/plugins/size-limit/package.json
- packages/knip/src/plugins/size-limit/index.ts
I use size-limit with `@size-limit/file` plugin.
Here is my `.size-limit.json`:
```json
[
{
"name": "Home Page",
"path": [
"dist/en.html",
"dist/_astro/*.js",
"!dist/_astro/BlogShare.*.js",
"!dist/_astro/TimelineData.*.js",
"!dist/_astro/BlogShare.*.js"
],
"limit": "40 kB",
"brotli": true
},
{
"name": "All Scripts",
"path": ["dist/**/*.js"],
"limit": "35 kB",
"brotli": true
}
]
```
At this moment there is an error about size-limit usage:
```
Unused devDependencies
@size-limit/file  package.json:62:6
```
In this PR I added a `resolve` function that automatically detects and marks all dependencies starting with `@size-limit/` as used.
> Support size-limit plugins usage

- packages/knip/src/plugins/vitest/index.ts
Latest version started failing with:
```bash
export const toPosix = (value) => value.split(path.sep).join(path.posix.sep);
TypeError: value.split is not a function
at toPosix (<my-repo>/node_modules/knip/dist/util/path.js:9:41)
at <my-repo>/node_modules/knip/dist/plugins/vitest/index.js:93:13
at Array.map (<anonymous>)
at addAliases (<my-repo>/node_modules/knip/dist/plugins/vitest/index.js:91:39)
at Object.resolveConfig (<my-repo>/node_modules/knip/dist/plugins/vitest/index.js:112:29)
at async runPlugin (<my-repo>/node_modules/knip/dist/WorkspaceWorker.js:273:40)
at async WorkspaceWorker.runPlugins (<my-repo>/node_modules/knip/dist/WorkspaceWorker.js:314:13)
at async build (<my-repo>/node_modules/knip/dist/graph/build.js:94:35)
at async main …
```
> Fix add aliases crashing on obj

- packages/knip/src/plugins/astro/index.ts
- packages/knip/src/plugins/astro/resolveFromAST.ts
The Astro plugin currently uses hardcoded paths that start with `src/`, but Astro's configuration allows changing the `srcDir` setting (default is `'src'`). This causes incorrect path resolution and "Unresolved imports" errors when users configure a custom source directory in their `astro.config.js/ts`.
Example:
https://github.com/azat-io/azat-io/blob/main/astro.config.ts#L130
This PR enhances the Astro plugin to dynamically read the Astro configuration and respect the `srcDir` setting.
> Support custom srcDir in Astro plugin

- packages/knip/fixtures/plugins/vite/package.json
- packages/knip/fixtures/plugins/vite/vite.config.ts
- packages/knip/src/plugins/vite/helpers.ts
- packages/knip/src/plugins/vite/index.ts
I saw you added some AST functionality so thought I'd do another take on #903 and #904 !
Tested against my [original reproduction repo](https://github.com/mbacalan/knip-vite-react-emotion-repro) and seems to work well.
> Add support for Babel plugins used in Vite/React config

- bun.lock
- packages/knip/package.json
- packages/knip/src/util/resolve.ts
* Removed `enhanced-resolve`
* Added `oxc-resolver`
* Adjust `util/resolve` code for `oxc-resolver`
- All `yarn test` suits successful
- All `yarn test:smoke` suits successful
Haven't benchmarked this specifically, but I see about **50%** time improvement in the projects that I'm currently working on.
> Migrate enhanced-resolve to oxc-resolver

- packages/knip/fixtures/plugins/hardhat/hardhat.config.ts
- packages/knip/fixtures/plugins/hardhat/package.json
- packages/knip/schema.json
- packages/knip/src/plugins/hardhat/index.ts
- packages/knip/src/plugins/index.ts
- packages/knip/src/schema/plugins.ts
- packages/knip/src/types/PluginNames.ts
- packages/knip/test/plugins/hardhat.test.ts
Hardhat is a CLI tool that relies on the presence of a JS config file.  The `hardhat` package may or may not be imported.
This plugin is meant to do two things:
1. Add `hardhat.config.x` as an entry.
2. Skip warnings if `hardhat` is not imported anywhere.
Is the implementation correct?  I'm not sure about the `resolve` function.
> Add Hardhat plugin

- packages/knip/fixtures/plugin-overlap/node_modules/typedoc/package.json
- packages/knip/fixtures/plugin-overlap/package.json
- packages/knip/fixtures/plugin-overlap/tsconfig.json
- packages/knip/fixtures/plugin-overlap/typedoc.json
- packages/knip/fixtures/workspaces-plugin-overlap/node_modules/typedoc/package.json
- packages/knip/fixtures/workspaces-plugin-overlap/package.json
- packages/knip/fixtures/workspaces-plugin-overlap/packages/workspace-a/package.json
- packages/knip/fixtures/workspaces-plugin-overlap/packages/workspace-a/tsconfig.json
- packages/knip/fixtures/workspaces-plugin-overlap/packages/workspace-a/typedoc.json
- packages/knip/src/WorkspaceWorker.ts
- packages/knip/test/plugin-overlap.test.ts
- packages/knip/test/workspaces-plugin-overlap.test.ts
As suggested, adds `pluginName` to the `seen` mix.
> resolve issue with plugin overlap on config files

- packages/knip/tsconfig.json
The `baseUrl` tsconfig property caused my editor to autocomplete non-relative imports in #1087 and #1090.  This property is "not recommended": https://www.typescriptlang.org/tsconfig/#baseUrl.  I am not aware of any side effects that might result from removing it, and build seems to be successful.
> Remove `baseUrl` property from tsconfig

- packages/knip/fixtures/plugins/astro/src/pages/about/mdx-with-layout.mdx
- packages/knip/src/compilers/astro-mdx.ts
- packages/knip/src/compilers/compilers.ts
- packages/knip/src/compilers/index.ts
- packages/knip/src/compilers/mdx.ts
- packages/knip/test/plugins/astro.test.ts
Treats the layout in the mdx frontmatter in an Astro project as an import.
Related Issue: #1084
> feat(astro-mdx): add compiler for @astrojs/mdx to treat layout value from mdx frontmatter as import

- packages/knip/fixtures/plugins/storybook2/.rnstorybook/index.tsx
- packages/knip/fixtures/plugins/storybook2/.rnstorybook/main.ts
- packages/knip/fixtures/plugins/storybook2/.rnstorybook/preview.tsx
- packages/knip/fixtures/plugins/storybook2/components/Button/Button.stories.tsx
- packages/knip/fixtures/plugins/storybook2/node_modules/storybook/package.json
- packages/knip/fixtures/plugins/storybook2/package.json
- packages/knip/src/plugins/storybook/index.ts
- packages/knip/test/plugins/storybook2.test.ts
Adds support for @storybook/react-native v9.
Used https://github.com/dannyhw/react-native-storybook-starter as basis for new fixtures. 
Related Issue: #1117
> feat(storybook): add support for Storybook React Native v9

- packages/knip/src/plugins/vue/index.ts
Since Vue CLI 5, vue.config.mjs is also recognized as the Vue config file
> Recognize vue.config.mjs

- biome.json
- packages/knip/biome.json
Currently, we allow `format` script inside `packages/knip` but the default config in `knip` package is not on par with the root `biome.json`. This can lead to unrelated diff as in https://github.com/webpro-nl/knip/pull/1113/commits/ba0c5ca23c1ebb4dffb5a531c638598bf0eb980d.
As a plugin writer, I needed to run `bun test test/plugins/biome.test.ts` inside `packages/knip`. Unfortunately, I had to run `bun run format` at the root folder to avoid the unintended diff. It mandates an extra step in the developer workflow.
This PR is to improve the ergonomic when running `bun run format` inside `packages/knip`. Moving forward, we can define `packages/knip`-specific biome config inside `package/knip/biome.json`.
> Restructure biome configurations

- packages/knip/src/plugins/react-router/index.ts
- packages/knip/test/plugins/react-router.test.ts
Due to this bug fix: https://github.com/webpro-nl/knip/pull/988 the entries on Windows are completely broken due to a transform happening midway between the plugin and the final resolver which turns the escaped \ \ into /.
I couldn't pinpoint the exact cause, and this fix mostly covers the issues on Windows, the only thing that won't work is the ( ) escape.
> Reverted change in the react-router plugin on windows

- packages/knip/fixtures/plugins/angular2/angular.json
- packages/knip/fixtures/plugins/angular2/package.json
- packages/knip/src/plugins/angular/index.ts
Angular plugin didn't detect Karma related dependencies after migrating to `@angular/build` builder (from `@angular-devkit/build-angular`). Here we allow for detecting Karma dependencies in both scenarios.
Angular 2 tests have been updated to use `@angular/build` to take these new builders into account in general too
PD: [Angular is migrating to `@angular/build` package for builders as has less dependencies if using the new build system](https://github.com/angular/angular-cli/pull/27520)
> Fix Angular plugin to allow for @angular/build

- packages/knip/fixtures/exports-special-characters/exports.ts
- packages/knip/fixtures/ignore-exports-used-in-file-id-underscores/imported.ts
- packages/knip/fixtures/ignore-exports-used-in-file-id-underscores/index.ts
- packages/knip/fixtures/ignore-exports-used-in-file-id-underscores/knip.json
- packages/knip/fixtures/ignore-exports-used-in-file-id-underscores/namespace.ts
- packages/knip/fixtures/ignore-exports-used-in-file-id-underscores/package.json
- packages/knip/fixtures/ignore-exports-used-in-file-id-underscores/tsconfig.json
- packages/knip/src/typescript/ast-helpers.ts
- packages/knip/test/exports-special-characters.test.ts
- packages/knip/test/ignore-exports-used-in-file-id-underscores.test.ts
**Bug**
knip fails to detect that an identifier beginning with two underscores is used when accessed as a namespace property.
**Example**
```
// exports.js
export const __foo = 1;
// imports.js
import * as NS from "./exports.js";
console.log(NS.__foo);
```
**Explanation**
In the above example, the export of `__foo` is processed [here](https://github.com/webpro-nl/knip/blob/cbfb9c3b1c6fd4f77b5e5f0987e0f027ee609feb/packages/knip/src/typescript/visitors/exports/exportKeyword.ts). Importantly, the identifier name is obtained using `getText()`.
However, the namespace property access `NS.__foo` is processed [here](https://github.com/webpro-nl/knip/blob/cbfb9c3b1c6fd4f77b5e5f0987e0f027ee609feb/packages/knip/src/typescript/ast-helpers.ts#L184) using `node.name.escapedText`. For identifiers that …
> Correctly detect used/unused namespace exports that begin with double underscores

- packages/knip/biome.json
- packages/knip/fixtures/plugins/biome-workspace/biome.jsonc
- packages/knip/fixtures/plugins/biome-workspace/node_modules/@biomejs/biome/package.json
- packages/knip/fixtures/plugins/biome-workspace/node_modules/@org/shared-configs/biome.json
- packages/knip/fixtures/plugins/biome-workspace/node_modules/@org/shared-configs/package.json
- packages/knip/fixtures/plugins/biome-workspace/package.json
- packages/knip/fixtures/plugins/biome-workspace/packages/stub/biome.json
- packages/knip/fixtures/plugins/biome-workspace/packages/stub/package.json
- packages/knip/src/plugins/biome/index.ts
- packages/knip/src/util/resolve.ts
- packages/knip/test/plugins/biome-workspace.test.ts
> Related issue https://github.com/webpro-nl/knip/issues/1154
Since biome 2.0.0, they introduce support for workspace support and a new format for extends that can now be either an array of config to extends (same behavior than previous major version) or a reference to the workspace with a new "micro-syntax" (explained here https://biomejs.dev/guides/big-projects/#monorepo) (eg: `{ "extends: "//" }` will mean extends root workspace config)
- Updated the biome plugin `resolveConfig` in order to handle new extends format (either single or array)
- Resolve `"extends": "//"` -> `"extends": "[workspaceroot]/biome.(json|jsonc}"`
I'm still exploring project, I have added a new basic fixtutre `biome-workspace` in order to test this behavior, I would love to have some guidance here in order to add …
> Support new biome config extends definition 

- packages/knip/fixtures/plugins/vitest9/package.json
- packages/knip/fixtures/plugins/vitest9/packages/client/e2e-setup.ts
- packages/knip/fixtures/plugins/vitest9/packages/client/e2e/client.test.ts
- packages/knip/fixtures/plugins/vitest9/packages/client/package.json
- packages/knip/fixtures/plugins/vitest9/packages/client/vitest.config.e2e.ts
- packages/knip/fixtures/plugins/vitest9/src/example.test.ts
- packages/knip/fixtures/plugins/vitest9/src/unit.setup.ts
- packages/knip/fixtures/plugins/vitest9/vitest.config.ts
- packages/knip/src/plugins/vitest/index.ts
- packages/knip/src/plugins/vitest/types.ts
- packages/knip/test/plugins/vitest9.test.ts
Adds support for Vitest's `projects` configuration that allows defining test projects through inline configurations and external file patterns. External project files are resolved from glob patterns and their dependencies are correctly assigned to their respective workspace locations.
Resolves #1114
- Added `projects` field to VitestConfig interface supporting both inline configs and glob patterns
- Implemented dynamic glob resolution for external project files using `_glob` utility
- External project configurations loaded using `toConfig()` for proper workspace assignment
- Created test fixture with both inline and external project configurations
- Dependencies from external projects are correctly attributed to their respective config files
- All existing tests pass
- New vitest9 test …
> Support Vitest projects configuration for dynamic project discovery

- packages/knip/src/schema/configuration.ts
Adds [tsdoc](https://tsdoc.org/) for showing schema documentation in IDE.
- Add TSdoc for all config in the Plugins
- Defined in a different file and need to understand better first how the plugin generation process might be affected.
Closes #892
> docs: only add TSDoc for configuration

- packages/knip/src/plugins/rspack/index.ts
My project is using an `.mts` file extension for our Rspack config, and I noticed that it wasn't getting automatically included.
> Rspack plugin: add mts and cts file extension support

- packages/knip/src/binaries/fallback.ts
- packages/knip/test/util/get-inputs-from-scripts.test.ts
[`env-cmd`](https://github.com/toddbluhm/env-cmd) just had a v11 release that enforces `--` usage like `dotenvx` - this PR adds support for it.
If you're wondering why someone would use `env-cmd` over `dotenvx` - `env-cmd` has different behavior (doesn't do a load of logging), different defaults (overriding existing env vars), and supports more file formats (JSON etc.) - which is crucial when you don't have control over the format (for example, Google Cloud Functions require JSON dotenv files).
> Add `env-cmd` Support

- packages/knip/fixtures/plugins/rslib/package.json
- packages/knip/fixtures/plugins/rslib/rslib.config.ts
- packages/knip/src/plugins/rslib/index.ts
- packages/knip/test/plugins/rslib.test.ts
The rslib package is `@rslib/core`, not `rslib`
Fixes: #1226
> Fix package name of rslib enabler

- packages/knip/src/constants.ts
IMO these binaries are common enough to be ignored globally.
Both have packages of the same name on npm that are older than 6 years
[`unzip` last published 11 years ago](https://www.npmjs.com/package/unzip)
[`time` last published 9 years ago](https://www.npmjs.com/package/time)
> feat: add `time` & `unzip` to ignored binaries

- packages/knip/fixtures/plugins/vitest/package.json
- packages/knip/src/plugins/vitest/index.ts
Detect vitest ui mode (`vitest --ui`) and add `@vitest/ui` as optional dependency.
Similar to how the eslint plugin does it with the config inspector.
https://vitest.dev/guide/ui
> feat: detect vitest ui mode
